### ISSUE TITLE
Please consider a `requirements.txt` for this script

### ISSUE THREAD

**Issue by patsytau** [cjdb/new_cxx_project#11]
### Is your feature request related to a problem? Please describe

When attempting to run `./new_cxx_project.py` after a fresh clone, I receive the following message: `ModuleNotFoundError: No module named 'git'`, and no output files are generated. Searching on PyPI (https://pypi.org/search/?q=git) shows a large number of git-related modules, and I don't know which one to install.

### Describe the solution you'd like

It would be helpful if you could provide a `requirements.txt` in the root of the repository, for those modules that are necessary to run the script.

### Describe any alternatives that you've considered

These could be listed in the README.md, but I believe this would be less user-friendly.

Depending on exactly what is being done, the dependency on the `git` module might be able to be removed, by running git commands via `subprocess.run(...)`.

**Comment by cjdb** [comment]
Thanks for reporting this! I'm actually working on something similar at the moment. Would you like me to tag you as a reviewer?

**Comment by patsytau** [comment]
Certainly! Thanks for looking into it :)
